In [1]:
import numpy as np
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [4]:
b = a [2:4,0:2]
print(b)

[[11 12]
 [16 17]]


In [5]:
c = a.diagonal(offset=1)
c

array([ 2,  8, 14, 20])

In [13]:
x1=a[0,1]
x2=a[1,2]
x3=a[2,3]
x4=a[3,4]
x0 = np.array([np.array(x1),np.array(x2),np.array(x3),np.array(x4)])
print(x0)

[ 2  8 14 20]


In [6]:
d = a [[0,4,5],3:5]
d

array([[ 4,  5],
       [24, 25],
       [29, 30]])